export const MOCK_CAREERS = [
  {
    id: "frontend-developer",
    title: "Frontend Developer",
    matchScore: 92,
    salary: "$105,000",
    salaryValue: 105000,
    education: "Bachelor's or Bootcamp",
    growth: "+8%",
    growthValue: 8,
    timeToLearn: "6-9 months",
    skills: ["React", "JavaScript", "CSS", "Next.js", "TypeScript"],
    courses: ["Meta Front-End Developer", "Namaste React"],
    roadmapSummary: "Focus on mastering JS fundamentals, then React, followed by advanced state management and performance optimization.",
    description: "Build user interfaces and highly interactive web applications.",
    color: "bg-blue-500/10 border-blue-500/20 text-blue-500",
  },
  {
    id: "backend-developer",
    title: "Backend Developer",
    matchScore: 85,
    salary: "$120,000",
    salaryValue: 120000,
    education: "Bachelor's in CS",
    growth: "+10%",
    growthValue: 10,
    timeToLearn: "9-12 months",
    skills: ["Node.js", "Python", "SQL", "Docker", "AWS"],
    courses: ["IBM Backend Development", "Complete Node.js Developer"],
    roadmapSummary: "Learn APIs, databases, authentication, and deployment. Master at least one backend language and database.",
    description: "Design and build server-side logic, APIs, and databases.",
    color: "bg-emerald-500/10 border-emerald-500/20 text-emerald-500",
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    matchScore: 78,
    salary: "$95,000",
    salaryValue: 95000,
    education: "Design Degree or Portfolio",
    growth: "+15%",
    growthValue: 15,
    timeToLearn: "4-6 months",
    skills: ["Figma", "User Research", "Wireframing", "Prototyping"],
    courses: ["Google UX Design", "Figma UI UX Design Essentials"],
    roadmapSummary: "Master Figma, understand user psychology, build a portfolio of 3 solid case studies.",
    description: "Design intuitive user experiences and beautiful interfaces.",
    color: "bg-purple-500/10 border-purple-500/20 text-purple-500",
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    matchScore: 65,
    salary: "$130,000",
    salaryValue: 130000,
    education: "Master's or Ph.D.",
    growth: "+22%",
    growthValue: 22,
    timeToLearn: "12-18 months",
    skills: ["Python", "Machine Learning", "SQL", "Statistics"],
    courses: ["IBM Data Science", "Machine Learning by Stanford"],
    roadmapSummary: "Learn Python and Math, explore data manipulation, learn ML algorithms, and build end-to-end models.",
    description: "Analyze complex data to help companies make better decisions.",
    color: "bg-rose-500/10 border-rose-500/20 text-rose-500",
  },
  {
    id: "product-manager",
    title: "Product Manager",
    matchScore: 88,
    salary: "$115,000",
    salaryValue: 115000,
    education: "Bachelor's Degree",
    growth: "+11%",
    growthValue: 11,
    timeToLearn: "6-12 months",
    skills: ["Agile", "Strategy", "Communication", "Data Analysis"],
    courses: ["Google Project Management", "Product Management 101"],
    roadmapSummary: "Understand SDLC, practice user interviews, learn agile frameworks, build a product from scratch.",
    description: "Guide the success of a product and lead the cross-functional team.",
    color: "bg-amber-500/10 border-amber-500/20 text-amber-500",
  }
];
