# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Check for pending Prisma migrations
      env:
        DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
        SHADOW_DATABASE_URL: ${{ secrets.CI_SHADOW_DATABASE_URL }}
      run: |
        # Fail if schema.prisma differs from migrations on disk
        npx prisma migrate diff --from-migrations ./prisma/migrations --to-schema-datamodel prisma/schema.prisma --shadow-database-url $SHADOW_DATABASE_URL --exit-code

    - name: Generate Prisma client
      run: npx prisma generate
    - run: npx playwright install --with-deps chromium
    - run: npm run test:unit
    - run: npm run build --if-present
    - run: npm run test:e2e
